language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email:
    - daniel@desarrolla2.com

before_script:
  - cp phpunit.xml.dist phpunit.xml
  - composer install --prefer-source --no-interaction
